### ISSUE TITLE
Missing ports on docker - Bin is working properly

### ISSUE THREAD

**Issue by Komodoro** [rpetti/blackduck_exporter#1]
Hello, 

I'm having trouble in running your container out of the box as it is.
No ports are showing after:
`docker ps`
In the containers that are running.

But I'm able to run the bin file after building the blackduck_exporter.go with the instructions as you had in your **dockerfile**:
`go get -d -v && CGO_ENABLED=0 GOOS=linux go build -o blackduck_exporter .`

And doing:
`
./blackduck_exporter -blackduck.url=https://<my_url> -blackduck.username=<my_user> -blackduck.password=<my_password> -telemetry.address=:9125 -telemetry.endpoint=/metrics
`

I just needed to install the following dependencies on **go-1.9** folder on src on`/github.com/` and the run above works on my linux instance:

- beorn7/perks
- golang/glog
- golang/protobuf
- matttproud/golang_protobuf_extensions
- prometheus/client_golang
- prometheus/client_model
- prometheus/common
- prometheus/procfs

In a certain way the container would be great help for my scenario but I dunno what I need to do to make the proper changes so that it could work. I'm a new to docker and I dunno if in yours is working as it should and if this is a bug of some sort.
Can you help?

But great work with this exporter. Congrats. 

Thanks in advance.

**Comment by h0ll0wl** [comment]
One quick fix is to manually assign the ports, using the flag **-p**
When using this flag is **-p host_port:container_port**
Also quick tip you can run the container in detached mode using the flag **-d**.
This way you can be running the container in background and still use the terminal (if it's your case) for other works. In the end just use **docker stop <container_id or container_name>** so it stops running the container.  
So when you start the container you should do the following:
docker run **-d** **-p 9125:9125** rpetti/blackduck_exporter \
    -blackduck.url=https://yourblackduckserver.com \
    -blackduck.username=blackduck_user \
    -blackduck.password.file=/file/containing/password \
    -telemetry.address=:9125 \
    -telemetry.endpoint=/metrics

**Comment by Komodoro** [comment]
> 
> 
> One quick fix is to manually assign the ports, using the flag **-p**
> When using this flag is **-p host_port:container_port**
> Also quick tip you can run the container in detached mode using the flag **-d**.
> This way you can be running the container in background and still use the terminal (if it's your case) for other works. In the end just use **docker stop <container_id or container_name>** so it stops running the container.
> So when you start the container you should do the following:
> docker run **-d** **-p 9125:9125** rpetti/blackduck_exporter
> -blackduck.url=https://yourblackduckserver.com
> -blackduck.username=blackduck_user
> -blackduck.password.file=/file/containing/password
> -telemetry.address=:9125
> -telemetry.endpoint=/metrics

This has fixed my situation. I was unaware of this kind of situation and possibility and need. I thought the whole container would do the job by itself. Thanks a lot for the solution.
Great work.
